# Generated by Django 2.2.9 on 2022-05-09 16:13

import contact.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[contact.models.validate_name])),
                ('phone_num', models.BigIntegerField(unique=True)),
                ('address', models.CharField(default='Y', max_length=255)),
            ],
            options={
                'db_table': 'EMPLOYEE_MASTER',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('empref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
            ],
            options={
                'db_table': 'Group_db',
                'ordering': ['name'],
            },
        ),
    ]
