# Generated by Django 2.2.9 on 2022-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_delete_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['role']},
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(default='Guest', max_length=30),
        ),
    ]
